### ISSUE TITLE
Remove command from sideMenu Not working

### ISSUE THREAD

**Issue by Bitxenio** [codenameone/ToolbarSidemenu#1]
I'm having some trouble modifying SideMenu commands since the last JavaSE update.

Test case below shows the problem. Expected result is: clicking on the command will remove it. Actual result is: clicking in the command doesn't seem to do anything.

Toolbar.setGlobalToolbar(true);
Form hi = new Form("Entrada");
Style s = UIManager.getInstance().getComponentStyle("TitleCommand");
FontImage icon = FontImage.createMaterial(FontImage.MATERIAL_WARNING, s);

Command cmd = hi.getToolbar().addCommandToRightBar("Bla", null, (e) -> Log.p("Bla"));
hi.getToolbar().addCommandToSideMenu("Remove", null, (e) -> {
  hi.removeCommand(cmd);
  hi.revalidate();
});

Also, after adding commands to the sidebar, hi.getCommandCount() returns 0

**Comment by codenameone** [comment]
Thanks this should be fixed now

**Comment by Bitxenio** [comment]
Bug is still present. Removing commands from the RightBar works (now), but removing them from the side menu still doesn't. I attach a new test case.

Toolbar.setGlobalToolbar(true);
Form hi = new Form("Entrada");
Style s = UIManager.getInstance().getComponentStyle("TitleCommand");
FontImage icon = FontImage.createMaterial(FontImage.MATERIAL_WARNING, s);

Command cmd = hi.getToolbar().addCommandToSideMenu("Bla", null, (e) -> Log.p("Bla"));
hi.getToolbar().addCommandToSideMenu("Remove", null, (e) -> {
hi.removeCommand(cmd);
hi.revalidate();
});

I tried calling removeCommand() also from outside the sideMenu, but the behaviour is the same.

In the old sidemenu (setting Toolbar.setOnTopSideMenu(false)) everything works.
